plugins {
	id "io.spring.convention.root"
}

group = projectGroup
description = "Spring Authorization Server"

develocity {
	buildScan {
		termsOfUseUrl = 'https://gradle.com/help/legal-terms-of-use'
		termsOfUseAgree = 'yes'
	}
}

allprojects {
	repositories {
		maven {
			name = 'nexus'
			url = nexusPublicUrl
			allowInsecureProtocol = true
			credentials {
				username = nexusUsername
				password = nexusPassword
			}
		}
		if (version.endsWith('-SNAPSHOT')) {
			maven {
				name = 'nexusSnapshot'
				url = nexusSnapshotUrl
				allowInsecureProtocol = true
				credentials {
					username = nexusUsername
					password = nexusPassword
				}
			}
		}
		mavenCentral()
	}
}

// 配置发布到 Nexus 私服
subprojects {
	plugins.withType(MavenPublishPlugin) {
		publishing {
			repositories {
				maven {
					name = 'nexus'
					url = project.version.toString().endsWith('-SNAPSHOT') ? nexusSnapshotUrl : nexusReleaseUrl
					allowInsecureProtocol = true
					credentials {
						username = nexusUsername
						password = nexusPassword
					}
				}
			}
		}
	}
}
