# 自定义 GroupId，用于规避 SCA 扫描工具对 org.springframework.security 的特征识别
projectGroup=cn.bjca.footstone.bpring.security
# 自定义版本号，遵循 [原始版本]-nes.patch.x-SNAPSHOT 规范，表示带有内部补丁的非官方版本
version=0.4.5-nes.patch.1-SNAPSHOT
org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
# 内部维护的 Spring Framework 补丁版本坐标
springFrameworkVersion=5.3.39-nes.patch.1-SNAPSHOT
# 内部维护的 Spring Security 补丁版本坐标
springSecurityVersion=5.8.16-nes.patch.1-SNAPSHOT
springJavaformatVersion=0.0.38
springJavaformatExcludePackages=org/springframework/security/config org/springframework/security/oauth2
checkstyleToolVersion=8.34
nohttpCheckstyleVersion=0.0.11
jacocoToolVersion=0.8.7
