# 自定义 GroupId，用于规避 SCA 扫描工具对 org.springframework.security 的特征识别
projectGroup=cn.bjca.footstone.bpring.security
# 自定义版本号，遵循 [原始版本]-nes.patch.x-SNAPSHOT 规范，表示带有内部补丁的非官方版本
version=1.5.8-nes.patch.1-SNAPSHOT
org.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true
org.gradle.caching=true
# 内部维护的 Spring Framework 补丁版本坐标
springFrameworkVersion=6.2.19-nes.patch.1-SNAPSHOT
# 内部维护的 Spring Security 补丁版本坐标
springSecurityVersion=6.5.11-nes.patch.1-SNAPSHOT
